function hfssCreateRelativeCS(fid, Name, Origin, XAxisVec, YAxisVec, Units)
XAxisVec = reshape(XAxisVec, length(XAxisVec), 1);
YAxisVec = reshape(YAxisVec, length(YAxisVec), 1);
if iscell(XAxisVec) ~= 1
    XAxisVec = mat2cell(XAxisVec,[1,1,1],1);
end
if iscell(YAxisVec) == 0
    YAxisVec = mat2cell(YAxisVec,[1,1,1],1);
end

fprintf(fid, '\n');
fprintf(fid, 'oEditor.CreateRelativeCS Array("NAME:RelativeCSParameters", _\n');

fprintf(fid, '"OriginX:=", "%f%s", _\n', Origin(1), Units);
fprintf(fid, '"OriginY:=", "%f%s", _\n', Origin(2), Units);
fprintf(fid, '"OriginZ:=", "%f%s", _\n', Origin(3), Units);


xyz = ['XYZ'];
for i = 1:3
    if isnumeric(XAxisVec{i,1})
        fprintf(fid, '"XAxis%svec:=", "%f%s", _\n', xyz(i), XAxisVec{i,1}, Units);
    else
        fprintf(fid, '"XAxis%svec:=", "%s", _\n', xyz(i), XAxisVec{i,1});
    end
end

for i = 1:2
    if isnumeric(YAxisVec{i,1})
        fprintf(fid, '"YAxis%svec:=", "%f%s", _\n', xyz(i), YAxisVec{i,1}, Units);
    else
        fprintf(fid, '"YAxis%svec:=", "%s", _\n', xyz(i), YAxisVec{i,1});
    end
end
if isnumeric(YAxisVec{3,1})
    fprintf(fid, '"YAxis%svec:=", "%f%s"), _\n', xyz(3), YAxisVec{3,1}, Units);
else
    fprintf(fid, '"YAxis%svec:=", "%s"), _\n', xyz(3), YAxisVec{3,1});
end

fprintf(fid, 'Array("NAME:Attributes", _\n');
fprintf(fid, '"Name:=", "%s")', Name);
